### ISSUE TITLE
Can't detect media keys on composite HID device

### ISSUE THREAD

**Issue by CyberAndrew** [evilC/AutoHotInterception#104]
I have RF remote with USB dongle.
It acts like usual HID-keyboard (HID_DEVICE_SYSTEM_KEYBOARD), mouse (HID_DEVICE_SYSTEM_MOUSE).

Except media keys: volume up, down, prev, next song etc.
For unknown reason, these media keys are sent from third "HID-compliant control device" (hid type "HID_DEVICE_SYSTEM_CONSUMER").

Any idea how to input these media keys to AHI?

**Comment by evilC** [comment]
https://github.com/evilC/AutoHotInterception/issues/109#issuecomment-1962704769
