### ISSUE TITLE
Monitor.AHK Error

### ISSUE THREAD

**Issue by Rew7247** [evilC/AutoHotInterception#107]
When I try to run Monitor.ahk I get this message 
<img width="235" alt="opera_DSRa7igMUy" src="https://github.com/evilC/AutoHotInterception/assets/141793059/42ea1395-ee11-4a25-9921-66189860d6a1">
I don't understand why it wont work.

**Comment by sirNugg3ts** [comment]
You are probably running the wrong version of AHK

**Comment by Rew7247** [comment]
Thanks I got it working I ended up having to edit one of the files to get it to work

**Comment by c33s** [comment]
@Rew7247 would be nice if you would share your solution here
