### ISSUE TITLE
[Fix] Unable to find AutoHotInterception.dll

### ISSUE THREAD

**Issue by OSsqirat** [evilC/AutoHotInterception#110]
Just download it from an older version on the Release Page and put it in the Lib folder... and it should work... I believe The new version forgot to add that folder.

I formatted my pc and downloaded the newer version to this date and it did the same issue because in the newer version the "AutoHotInterception.dll" in not included in the lib folder for some reason...

once you add it from a previous version to the newest version ... it should be running good.

https://imgur.com/h0ycL1t

**Comment by evilC** [comment]
As per the instructions, it's in the `Common\Lib` folder inside the zip
![image](https://github.com/evilC/AutoHotInterception/assets/1719428/47197a85-8b66-4ef6-bc02-7099f4465cc6)
