### ISSUE TITLE
Send horizontal wheel reported as non-working

### ISSUE THREAD

**Issue by evilC** [evilC/AutoHotInterception#19]
https://autohotkey.com/boards/viewtopic.php?p=227512#p227512

**Comment by MartinLichtblau** [comment]
Talking about `AHI.SendMouseButtonEvent(scrollMouseId, 6, -1)`? 
Works for me! Smoother than any AHK method!

**Comment by evilC** [comment]
This was fixed some time ago, I forgot to close issue
