### ISSUE TITLE
Bonus: UAC override

### ISSUE THREAD

**Issue by MartinLichtblau** [evilC/AutoHotInterception#25]
An advantage worth mentioning is that it can trick UAC; the windows admin security check. There are many more advantages, that aren't obvious. Should add those in the description/doc.

**Comment by evilC** [comment]
I would really rather not advertise that AHI can be used for such nefarious purposes.  
Besides, if you need to auto-elevate an AHK script, you can use [RunAsTask](https://www.autohotkey.com/boards/viewtopic.php?t=4334)

**Comment by MartinLichtblau** [comment]
Didn't mean it like this. Anyway...
Another bonus: the send commands go even deeper than the windows key registry remaps.
