### ISSUE TITLE
Bad assertion for UnsubscribeMouseButton function

### ISSUE THREAD

**Issue by crumbl3d** [evilC/AutoHotInterception#31]
Looks like the function checks whether the specified id is a keyboard instead of the mouse. The following change needs to be made in [Manager.cs](https://github.com/evilC/AutoHotInterception/blob/f7768b21cb850c914134a5eb3fb4c55d019b80a7/C%23/AutoHotInterception/Manager.cs#L121):
```
IsValidDeviceId(false, id);
```
needs to be
```
IsValidDeviceId(true, id);
```

**Comment by evilC** [comment]
Fixed in 0.4.1
