### ISSUE TITLE
Dear EviLC,Can AHI work like Taran's intercept veido?

### ISSUE THREAD

**Issue by TaranGenius** [evilC/AutoHotInterception#49]
https://www.youtube.com/watch?v=y3e_ri-vOIo&list=PL2DzFnV-Dr4YaZE2jIJNWsi_wEZCoFFqF&index=4&t=0s

**Comment by evilC** [comment]
AFAIK, It can do everything that Intercept can do, and more
Plus, you do not need to wrap keystrokes in keystrokes (No need to use F24 to wrap keys)
